# Generated by Django 3.1.5 on 2021-02-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagehandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.FileField(upload_to='imagebazaar'),
        ),
    ]
