# Generated by Django 3.1.5 on 2021-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagehandler', '0002_auto_20210207_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='imagebazaar'),
        ),
    ]
